### ISSUE TITLE
Canvas incorrectly states camelcase when it should be pascalcase. 

### ISSUE THREAD

**Issue by swilson-pro** [learn-co-curriculum/phase-3-active-record-writing-migrations-lab#4]
### Canvas Link

https://learning.flatironschool.com/courses/5208/assignments/199429?module_item_id=451177

### Concern

Hi there,

throughout this module, it is repeated several times that we should use CamelCase for class names. It should be pascal case. example is here: https://learning.flatironschool.com/courses/5208/assignments/199429?module_item_id=451177

### Additional Context

..

### Suggested Changes

change it to pascal case

**Comment by lizbur10** [comment]
Hi @swilson-pro - thanks for catching this! The error has been corrected in this lab and in the Classes and Instances lesson.

Thanks for contributing to the Flatiron School curriculum 💙
